### ISSUE TITLE
Development URLs for offline templates cached too aggressively

### ISSUE THREAD

**Issue by iandunn** [GoogleChromeLabs/pwa-wp#167]
It seems like the testing URLs for the offline templates (i.e., `/?wp_error_template=(offline|500)` are aggressively cached, and some times ~5 hard refreshes (`command + shift + R`) are needed to see the changes, even though they appear immediately when making requests via `curl`.

I'm guessing that some of the service worker caching is being applied to them. It seems like those specific URLs should be excluded from any additional caching that the plugin does, due to their nature.

**Comment by iandunn** [comment]
#110 seems related, but not necessarily a duplicate.

**Comment by westonruter** [comment]
This is expected because those URLs are precached by the service worker. They will only be updated when the service worker updates, something which can be blocked by having multiple tabs open. The easiest way to test the the development of the offline page would be to click the “Bypass for network” checkbox in DevTools:

![image](https://user-images.githubusercontent.com/134745/59303067-47b4a380-8c4a-11e9-92a2-6e2fa5768afd.png)

**Comment by westonruter** [comment]
Precached URLs are essentially served with a `CacheFirst` strategy.

**Comment by iandunn** [comment]
Oh, I see. I was assuming that there were different URLs that were precached for the user, but it makes sense to reuse them.

Maybe the only thing to do here then is to document this for behavior, since I imagine a lot of other devs will run into this?

**Comment by iandunn** [comment]
I experienced a similar problem today. After adding or removing calls to `wp_register_service_worker_caching_route()` and `$scripts->precaching_routes()->register()`, Chrome still has `/?wp_service_worker=1` cached and doesn't see the changes, even after closing the Incognito window, reopening, and hard-refreshing 5x with `Update on reload` and `Bypass for network` checked and unchecked, `disable cache` checked, and no other tabs open for that site. 

That seems so counterintuitive and wrong that I'd assume I was making a mistake, if it weren't for the fact that Firefox picks up the changes after a single soft refresh with `Disable cache` checked in dev tools.

That seems like more a problem with Chrome than this plugin, but might be worth documenting if others can reproduce it.

**Comment by westonruter** [comment]
I think the confusion regarding the service worker not updating was addressed by #205 where it now discontinues skipWaiting by default. In other words, it will install the service worker update immediately even when there are other client windows open.
