### ISSUE TITLE
Document what integrations do

### ISSUE THREAD

**Issue by iandunn** [GoogleChromeLabs/pwa-wp#171]
It's not clear what the integrations actually do, unless you read through the code and connect the dots. Having a high-level `README` or even docblock description would help people understand whether or not it's something they'd like to try.

**Comment by westonruter** [comment]
I've finally got to this. In general, don't use the integrations 😄 Here is the documentation: https://github.com/GoogleChromeLabs/pwa-wp/wiki/Service-Worker#integrations
