### ISSUE TITLE
Document caching strategies

### ISSUE THREAD

**Issue by iandunn** [GoogleChromeLabs/pwa-wp#172]
The strategy names are descriptive, but probably won't be enough explanation for developers who haven't encountered them before. I think it'd be good to include a link to the [Workbox Strategies](https://developers.google.com/web/tools/workbox/modules/workbox-strategies) page in the readme, to provide the necessary background information, context, etc.

**Comment by westonruter** [comment]
Now added to https://github.com/GoogleChromeLabs/pwa-wp/wiki/Service-Worker#caching

**Comment by iandunn** [comment]
Thanks!
