### ISSUE TITLE
Add default args for navigation caching strategy

### ISSUE THREAD

**Issue by westonruter** [GoogleChromeLabs/pwa-wp#176]
Currently if you enable a navigation caching strategy, like Network-First:

```php
add_filter(
	'wp_service_worker_navigation_caching_strategy',
	function() {
		return WP_Service_Worker_Caching_Routes::STRATEGY_NETWORK_FIRST;
	}
);
```

You also have to configure it with arguments like this:

```php
add_filter(
	'wp_service_worker_navigation_caching_strategy_args',
	function( $args ) {
		$args['cacheName']                           = 'pages';
		$args['plugins']['expiration']['maxEntries'] = 50;
		return $args;
	}
);
```

However, in the several sites I've done this one, the args are always the same. The `cacheName` should never really need to change from site to site.

The `maxEntries` may need to be variable, but again, it seems like there should be a good default for this. For example, the fonts caching integration defaults to 30 entries:

https://github.com/xwp/pwa-wp/blob/eaed8fb7062ae510ce7309fe477902fbcc374810/integrations/class-wp-service-worker-fonts-integration.php#L43-L46

Should there also perhaps be a `maxAgeSeconds` for navigation requests caching?

**Comment by iandunn** [comment]
👍 It also felt kinda annoying to me that you had to use separate filters to set them, rather than just using a single one. Almost opened a ticket for that. Maybe that's not really an issue if there are common defaults, though.

**Comment by westonruter** [comment]
Yes, the need for there being separate filters is also annoying. If we can combine them into a single filter that would be good.

**Comment by westonruter** [comment]
See also #265.

**Comment by westonruter** [comment]
> Yes, the need for there being separate filters is also annoying. If we can combine them into a single filter that would be good.

In terms of merging two filters, one option would be after this:

https://github.com/GoogleChromeLabs/pwa-wp/blob/ec984523a90d94afe49ebf65f0ec419b026322d4/wp-includes/components/class-wp-service-worker-navigation-routing-component.php#L92-L110

To introduce a new `wp_service_worker_navigation_caching` filter that takes a filter that is a merged/flattened array of the strategy, strategy args, and the strategy args plugins:

```php
$plugins = $caching_strategy_args['plugins'];
unset( $caching_strategy_args['plugins'] );

$config = array_merge(
	array( 'strategy' => $caching_strategy ),
	$caching_strategy_args,
	$plugins
);

/**
 * Filters service worker caching configuration for navigation requests.
 *
 * @param array {
 *     Configuration.
 *
 *     @type string $strategy              Strategy. Defaults to NetworkFirst.
 *     @type int    $networkTimeoutSeconds Network timeout seconds.
 *     @type array  $expiration            {
 *          Expiration configuration.
 *
 *          @type int $maxEntries Max entries to cache.
 *     }
 * }
 */
$caching_strategy_args = apply_filters( 'wp_service_worker_navigation_caching', $config );
```

Inside of `WP_Service_Worker_Caching_Routes::prepare_strategy_args_for_js_export()` we'd put the `expiration` back inside of the `plugins` key as Workbox needs, but for the purposes of filtering all of these Workbox plugin configuration keys can be put at the toplevel, namely:

https://github.com/GoogleChromeLabs/pwa-wp/blob/ec984523a90d94afe49ebf65f0ec419b026322d4/wp-includes/components/class-wp-service-worker-caching-routes.php#L174-L178

I don't see there being any possibility for conflicts.

We could then deprecate the `wp_service_worker_navigation_caching_strategy` and `wp_service_worker_navigation_caching_strategy_args` filters.
