### ISSUE TITLE
HTTPS setting is not multisite-aware

### ISSUE THREAD

**Issue by iandunn** [GoogleChromeLabs/pwa-wp#209]
### Problem

In a Multisite network, it seems odd to show the HTTPS setting on individual sites. It seems like that'd be something that the network admin would often want to set globally.

Some networks will have cases where some sites have certs and some don't, though, so some kind of site-level setting is probably still needed.

### Possible Solution

Maybe there should be a Network setting that lets super admins choose to redirect to HTTPS for: `all sites`, `some sites`, and `never`. Then, the setting would only show up on individual sites when `some sites` was chosen.

_( The wording of those options is rough, and needs refinement )_

**Comment by westonruter** [comment]
Good point. This is also important to consider for multisite with subdirectory sites. If the main site has HTTPS, then all sites under it should also be HTTPS.

For subdomain multisite configurations, there could be more flexibility to enable/disable HTTPS for a given site, regardless of whether the main network site is using HTTPS.
