### ISSUE TITLE
Prototype App Shell in WordPress using AMP content

### ISSUE THREAD

**Issue by kevincoleman** [GoogleChromeLabs/pwa-wp#22]
- [ ] **To be validated by research from #12 before proceeding**: implementing an app shell site in WordPress introduces several of functional challenges.

AC1: Prototype a usage of app shells (built on #7), using a shelf for a menu or another dynamic feature of WordPress.
AC2: Make use of AMP Sanitization to increase stability in the app shell prototype

Many of the above challenges can be solved/removed if the site is sanitized, similar to what the AMP plugin does. Of course, sanitizing a site without replacing what’s cut out would just break the site, so reliance on the AMP sanitization process is pretty ideal for preparing a WordPress site for app shell implementation, since it preserves content integrity while also removing app shell blockers. In fact, one of the intended benefits of AMP is that [it makes content more embeddable](https://www.ampproject.org/docs/integration/pwa-amp/amp-in-pwa) for just such cases.

This issue could benefit from using key components from [Surma’s PWA](https://github.com/GoogleChromeLabs/ProgressiveWordPress).

**Comment by kevincoleman** [comment]
@kienstra, I worked with @westonruter to help gain clarity on the definition of this prototype—or at least the reasoning behind it. Please add any followup questions here.

**Comment by kienstra** [comment]
**Thanks**

Hi @kevincoleman,
Thanks for adding the ACs and details here.

**Comment by westonruter** [comment]
This should probably be worked on later on in the project. The app shell is somewhat of the culmination for what we're working toward.

**Comment by westonruter** [comment]
This should be worked on in the conference external of “1-line PWA” in AMP: https://github.com/ampproject/amphtml/issues/16589

**Comment by westonruter** [comment]
See also the seamless page transitions AMP issue: https://github.com/ampproject/amphtml/issues/12981

**Comment by amedina** [comment]
Saw a reference to[ an implementation](https://www.allmodern.com/) with an interesting alternative to the App Shell Model / SPA. It is an HTML streaming solution which "virtually" turns a Multi-page App into an Single-page App (along the lines of Jake Archibald's [the year of web streams](https://jakearchibald.com/2016/streams-ftw/)). Their implementation does not use Workbox, but Workbox has [a built in streaming module](https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.streams).

How it works

* Service worker pre-caches page header HTML
* Service worker responds to subsequent navigation requests by:
** Create HTML stream and immediately respond with cached header (browser renders it immediately)
** Simultaneously fetch page with added header to indicate it only needs the body from server
** Server returns page body and SW sends it to client in the stream

**Comment by westonruter** [comment]
@amedina that's super interesting. That would allow for creating an AMP-valid SPA without having to introduce a new AMP component to manage it. 

A complication is that the header and footer on a typical WordPress theme are not fixed; they typical change from page to page in some ways. For example, the class names in the nav menu, the metadata in the `head`, the header image shown, etc. So I'm not sure it would work as a general turn-key solution for turning a native AMP WordPress site into an SPA.

**Comment by amedina** [comment]
Thanks @westonruter; I agree. Not applicable directly as a turn-key solution on what we call "traditional WordPress".

**Comment by westonruter** [comment]
Then again, I wonder if the head metadata could be included in the body response encapsulated in JS that gets written into the `head`, then this JS could then delete itself from the document so the result would be valid AMP. But this seems like a hack in the AMP context because this approach wouldn't work on the AMP Cache.

**Comment by westonruter** [comment]
This can be seen in https://github.com/ampproject/amp-wp/pull/1519
