### ISSUE TITLE
Warn when no Site Icon set, when it is too small, or when a PNG is not being used

### ISSUE THREAD

**Issue by westonruter** [GoogleChromeLabs/pwa-wp#229]
The Lighthouse PWA audit flags a Web App Manifest that:

1. Is lacking an icon.
1. Has an icon that is less than 512px square. 
1. Is not a PNG.

These requirements should be enforced in the Customizer when selecting a site icon, and/or a warning notice should be shown with the Customizer control when the selected icon does not satisfy the requirements. This should also be added as a Site Health test.

**Comment by gziolo** [comment]
I run into this issue on my site that had an icon set a few years back. Related Twitter thread:
https://twitter.com/gziolo/status/1261338942328016896

![Screen Shot 2020-05-15 at 18 52 11](https://user-images.githubusercontent.com/699132/82078116-e65e4580-96e0-11ea-81bd-f391db31efbb.png)

**Comment by westonruter** [comment]
There should be a link from the Site Health test to the location where the Site Icon can be updated. As mentioned in https://github.com/GoogleChromeLabs/pwa-wp/issues/304#issuecomment-1030213168, Full Site Editing complicates this a bit since block-based themes don't have the Customizer.

**Comment by ankitrox** [comment]
@westonruter I will take this up from here and will look into possibilities to handle the mentioned scenarios.

**Comment by westonruter** [comment]
In addition to the Customizer, this should be implemented as a Site Health check. See also:

https://github.com/GoogleChromeLabs/pwa-wp/blob/928905ec46c22cce684155a26a7cad1800e89de8/wp-includes/class-wp-web-app-manifest.php#L246

The test should then have as one of its actions a link to go to the Customizer or Site Editor to edit the site icon. See related change for [short name test](https://github.com/GoogleChromeLabs/pwa-wp/pull/691#:~:text=The%20Site%20Health%20test%20for%20the%20Short%20Name%20now%20includes%20a%20link%20to%20the%20General%20Settings%20screen%20to%20manage%20the%20field).

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Warning messages are shown as expected.

https://user-images.githubusercontent.com/41000648/164016321-cf898f0e-1bc7-4781-b9bc-c53c732a4a66.mov
