### ISSUE TITLE
Offline/Cache setup with Service Worker

### ISSUE THREAD

**Issue by ToBulk** [GoogleChromeLabs/pwa-wp#230]
I have everything going so far. 

Only the offline functionality is still missing.

Is there a sample service worker so I don't have to start from scratch.

**Comment by westonruter** [comment]
Here's an example plugin that shows how configure PWA for offline: https://gist.github.com/westonruter/1a63d052beb579842461f6ad837715fb

**Comment by lkraav** [comment]
Curious, 0.3.0 was released 5 mo ago. Is it best to try things out on `master` code by now?

**Comment by westonruter** [comment]
I have been holding out on releasing the next version until Workbox 5 is released. I think that will be done in January now. Using `master` should be fine; it is stable as far as I know.

**Comment by westonruter** [comment]
Update: I am planning to release v0.4 on Monday.

**Comment by westonruter** [comment]
[v0.4.0](https://github.com/GoogleChromeLabs/pwa-wp/releases/tag/0.4.0) is now available.
