### ISSUE TITLE
! get_custom_header() in Custom_Header_Integration has no meaning

### ISSUE THREAD

**Issue by szepeviktor** [GoogleChromeLabs/pwa-wp#240]
[get_custom_header returns an object](https://developer.wordpress.org/reference/functions/get_custom_header/), so ! object it always false.

Discovered by @phpstan on Level 4

**Comment by westonruter** [comment]
Are you referring to this code:

https://github.com/GoogleChromeLabs/pwa-wp/blob/37a3365ff7d2c20541978be85525cd6140a37c4c/integrations/class-wp-service-worker-custom-header-integration.php#L57-L58

It's checking that the `attachment_id` is set, not the object as a whole.

**Comment by szepeviktor** [comment]
Rather this one:

https://github.com/GoogleChromeLabs/pwa-wp/blob/351eeeca0ef67e92c8db3e2f1cbf609572faeb1f/integrations/class-wp-service-worker-custom-header-integration.php#L22-L25

**Comment by westonruter** [comment]
The integrations will be deprecated per #403 so I'm closing this.
