### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Mululu** [GoogleChromeLabs/pwa-wp#245]
Hello,

Unfortunately the plugin does not work after I have installed it in WordPress.

What do I have to do to make this work?

Thanks a lot!

**Comment by westonruter** [comment]
Do you mean the service worker is still operating even though you have uninstalled the plugin?

**Comment by Mululu** [comment]
No, I installed the plugin from the Wordpress plugin directory. Unfortunately, the PWA does not work. Tested with my smartphone and Google Lighthouse.

Is there a howto somewhere how to install this app?

Thanks a lot!

**Comment by westonruter** [comment]
Oh, I misread your comment. 

Here is an example plugin that you can add that configures the PWA plugin to enable a network-first caching strategy which will allow previously-visited pages to be served offline: https://gist.github.com/westonruter/1a63d052beb579842461f6ad837715fb

**Comment by Mululu** [comment]
OK thanks, but why doesn't the PWA plugin work from the start or is it not intended for this? There are no settings anywhere.

Where do I have to insert your code or the file.

Lighthouse currently says that.
![Lighthouse](https://user-images.githubusercontent.com/5918495/74262917-14a54100-4cfe-11ea-8e92-959ad53c9db0.PNG)

**Comment by westonruter** [comment]
@Mululu The PWA plugin is intended to provide tools for you to create your own tailored experience. It's primarily a set of APIs.  We're still investigating what makes sense to bake-in as a default.  Having a network-first caching strategy as shown [in the above Gist](https://gist.github.com/westonruter/1a63d052beb579842461f6ad837715fb) is something that increasingly seems to make sense to be a default. 

The code is just a plugin. Add it to your `wp-content/plugins` directory and activate in the WP Admin.

**Comment by Mululu** [comment]
OK thanks for the clarification.  I was amazed that it didn't work right away.  I've used the Avada theme so far.  I installed the plugin there and it worked immediately.  In Lighthouse almost everything was green.  Now I want to switch to Elementor, for testing I installed the plugin but it doesn't work as expected.  Yes there are other PWA plugins but they don't work either.  I would also like to use this plugin because I have had good experience so far and because Google is a co-developer.  I still don't quite understand why the whole thing doesn't work now.  The code in Wordpress would probably have to be adjusted.  Maybe there will be a howto in the future.  Thank you very much @westonruter

**Comment by westonruter** [comment]
Yes, we need to provide more samples for how to leverage the plugin, and we need to include more use cases built into the plugin.

**Comment by Mululu** [comment]
Hi there,

unfortunately the plugin still doesn't work in context. Lighthouse says there is no manifest installed etc.

Where, in which file, do I have to insert something that the plugin works and Lighthouse shows everything green?

I hope I'm not too annoying.

Thank you very much!

**Comment by westonruter** [comment]
@Mululu What is the URL for the site that you are testing?
