### ISSUE TITLE
Remove canonical URL tag from wp_error_template

### ISSUE THREAD

**Issue by jono-alderson** [GoogleChromeLabs/pwa-wp#251]
`wp_error_template` templates, like this example in the wild - https://www.daysoftheyear.com/?wp_error_template=500 - contain a meta robots directive (`noindex, follow`) and a canonical URL tag.

The latter exposes other error paths, which may result in undesirable access and probing by search engines / other agents.

Given the presence of the `noindex` directive, the canonical URL tag can be safely+entirely removed.

**Comment by westonruter** [comment]
The PWA plugin is not adding a `canonical` link. Perhaps you have a plugin that is adding it?

> The latter exposes other error paths, which may result in undesirable access and probing by search engines / other agents.

What error paths are you referring to?

**Comment by jono-alderson** [comment]
Ah, looks like a conflict with some external kit. Will close this issue and go bug-hunting.
