### ISSUE TITLE
Unstyled admin bar appears when browsing cached pages offline

### ISSUE THREAD

**Issue by westonruter** [GoogleChromeLabs/pwa-wp#252]
When going offline in WordPress 5.4, the admin bar links are showing up the header like so:

> ![image](https://user-images.githubusercontent.com/134745/77501854-6caf8700-6e16-11ea-9e80-807f31950f8e.png)

I'm using this this Basic Site Caching plugin: https://gist.github.com/westonruter/1a63d052beb579842461f6ad837715fb

Granted, perhaps the problem is that this plugin is not adding the `admin-bar.css` to the runtime cache.  But at the same time, perhaps the admin bar should not show up at all when serving from cache?

**Comment by westonruter** [comment]
This will be addressed by #264.

**Comment by westonruter** [comment]
Maybe to fix this we should just add `/wp-admin/` to the list of routes that are cached?

**Comment by ankitrox** [comment]
@westonruter There are two things, I observed.

1. `admin-bar.css` file is being cached in core-assets in cache storage.
2. I am not able to reproduce the issue in WP 5.9 with `Twenty Twenty` theme.

If this is still the issue, can you walk me through steps to reproduce the same?

**Comment by westonruter** [comment]
> 1. `admin-bar.css` file is being cached in core-assets in cache storage.

Oh! So what this means is that this issue is obsolete. It was filed on March 2020 before the introduction of the core asset cache as part of #338, which was merged in December 2020. 

Aside: <del>This should also be mitigated by #436, in that if a user has Offline Browsing turned off then the offline/error page should not be cached at all in that case.</del> <ins>Actually, no as this is not about the offline page but rather cached pages.</ins>

**Comment by pooja-muchandikar** [comment]
As per this https://github.com/GoogleChromeLabs/pwa-wp/issues/252#issuecomment-1054480924 the issue seems to be invalid
