### ISSUE TITLE
Compatibility with OneSignal

### ISSUE THREAD

**Issue by aviz1** [GoogleChromeLabs/pwa-wp#275]
Hi, is this WP plugin compatible with OneSignal ?

I read here: https://documentation.onesignal.com/docs/onesignal-service-worker-faq#section-integrating-multiple-service-workers 

But I don't understand if I need to do something so will no conflict ?

**Comment by westonruter** [comment]
It is not compatible yet. However OneSignal is looking into this. See https://github.com/OneSignal/OneSignal-Website-SDK/issues/615.

**Comment by aviz1** [comment]
I am sorry, I don't understand what to do you make it work together and if it will be fixed.

**Comment by westonruter** [comment]
It is not currently compatible. OneSignal is working on it.

**Comment by maxhartshorn** [comment]
@westonruter Has the issue been addressed by OneSignal yet?

**Comment by westonruter** [comment]
No, work is still underway.
