### ISSUE TITLE
Auto Reload Web page in 2 sec

### ISSUE THREAD

**Issue by khabarsatta** [GoogleChromeLabs/pwa-wp#277]
Installed PWA plugin in wordpress . after installing webpage auto reloading every 2 se . so i dactivated plugin

**Comment by westonruter** [comment]
May be the same issue as https://github.com/GoogleChromeLabs/pwa-wp/issues/166 or https://github.com/GoogleChromeLabs/pwa-wp/issues/202.

In order to determine what the issue is for you, you'll need to share your site URL with the plugin active so I can determine the cause and provide a solution.

**Comment by khabarsatta** [comment]
https://khabarsatta.com my website url

**Comment by westonruter** [comment]
The issue is your site is already attempting to install a service worker: `FeedifySW.js`. Only one service worker can be installed installed in a given scope. The point of the PWA plugin is to provide an API to for multiple SW scripts to be combined into the one script that is installed as the service worker. However, you may need to work with Feedify for this to be possible. Currently their SW is being installed via: https://cdn.feedify.net/getjs/feedbackembad-min-3.0.js

To be compatible with a site's existing service worker, it's likely that Feedify would need to make a similar changes as OneSignal is investigating: https://github.com/OneSignal/OneSignal-Website-SDK/issues/615

**Comment by khabarsatta** [comment]
But i removed feedifysw.js before 5 to 10 days

**Comment by westonruter** [comment]
It's still there. I saw it being installed. You may have deleted the JS file but the code to install the SW file is still there.

In any case, the auto-reloading behavior will be removed with #205.

**Comment by khabarsatta** [comment]
Ok and please please can u tell me how can i delete feedify codes ... Please i finded on header , footer any where but not showing ... Please help me

**Comment by westonruter** [comment]
It's in this code appearing on your site:

```html
<script type="99dc0721fc7d348093701696-text/javascript">	var feedify = feedify || {};
	window.feedify_options={fedify_url:"https://feedify.net/",pkey:"BO3GwElzsHEh8opPhu4ugfZljT1a97ph-uRKAKPSD8OGEn4UBJrxBhQBLL_xtxAyyAJksjFLk4LIQv3c5mlEHwc"};
	(function (window, document){
		function addScript( script_url ){
			var s = document.createElement('script');
			s.type = 'text/javascript';
			s.src = script_url;
			document.getElementsByTagName('head')[0].appendChild(s);
		}
		addScript('https://tpcf.feedify.net/uploads/settings/7fafb97b51ab539a8beca343810b4ed9.js?ts='+Math.random());
		addScript('https://cdn.feedify.net/getjs/feedbackembad-min-3.0.js');
	})(window, document);
</script>
```

**Comment by khabarsatta** [comment]
Yes but how can i check this code add in xxx.php file

**Comment by westonruter** [comment]
I don't know. I don't know how you added it in the first place.

**Comment by khabarsatta** [comment]
I used feedify plugin... But before some dayes i dactivate and deleted

**Comment by westonruter** [comment]
Sorry, I don't know.

**Comment by khabarsatta** [comment]
Please Recheck .. I Removed all feedify scripts but facing same issue reloading page

**Comment by khabarsatta** [comment]
Please check one more tym i removed your privided scripts but facing sane issue

**Comment by westonruter** [comment]
I don't see the PWA plugin active, so I can't see the reported issue. No service worker is being installed.

**Comment by khabarsatta** [comment]
Now pwa is Active please check again :) Thanks in advance

**Comment by westonruter** [comment]
I did not see any auto-reload behavior with the service worker installed.

However, any reloading is going to be disabled as part of #205. So I suggest following that issue and testing the build when it is available (probably by today or tomorrow).

**Comment by khabarsatta** [comment]
But me and some user facing teloding issue ... Please clear catch and recheck

**Comment by westonruter** [comment]
I did check with a clear cache. I don't see any reloading issue.

I do you just disabled added skip-waiting.

Please subscribe to #205 and test the build when it is available.

**Comment by khabarsatta** [comment]
Added add_filter( 'wp_service_worker_skip_waiting', '__return_false' );! This Filter and working Fine 
Thanks Alot

**Comment by khabarsatta** [comment]
its reloading in intalled app :(

**Comment by westonruter** [comment]
I've opened a PR to fix this and have a build for testing: https://github.com/GoogleChromeLabs/pwa-wp/pull/279#issuecomment-619637234.
