### ISSUE TITLE
CSP header filter may not play well with others

### ISSUE THREAD

**Issue by GaryJones** [GoogleChromeLabs/pwa-wp#290]
This method is a filter on `wp_headers` action:

https://github.com/GoogleChromeLabs/pwa-wp/blob/330c76bd37bf9ef3655361ea50c3acdb8e9fce59/wp-includes/class-wp-https-ui.php#L343-L346

If there is already some code that filters wp_headers to add a value for `Content-Security-Policy`, then this value wipes that out without any consideration for what may already be there.

Could the method be a bit more subtle and check for the presence of a `Content-Security-Policy`, and append `upgrade-insecure-requests` if it doesn't already exist / amend the value if there is a value that would conflict with that?

**Comment by westonruter** [comment]
Yes, that's a great point.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ the changes are reflecting as expected.

Before: 
<img width="535" alt="Screenshot 2022-04-21 at 2 37 53 PM" src="https://user-images.githubusercontent.com/41000648/164420989-96789760-a9d6-4a4d-a4db-0cd9b8442fef.png">


--

After: 

<img width="572" alt="Screenshot 2022-04-21 at 2 38 08 PM" src="https://user-images.githubusercontent.com/41000648/164421030-a713d4c1-1ec1-470b-92e7-2c379914099f.png">
