### ISSUE TITLE
Display notice if HTTPS is not enabled, use 301 code in redirect

### ISSUE THREAD

**Issue by kienstra** [GoogleChromeLabs/pwa-wp#56]
As a follow-up to #17:
* Display a notice if the `siteurl` and `home` (WordPress Address and Site Address) are HTTP, and HTTPS is not enabled (like if there's no certificate)
<img width="934" alt="display-notice" src="https://user-images.githubusercontent.com/4063887/44751240-3fd1ab80-aadd-11e8-9d05-db2d2bbdc7ff.png">

* Change the code in the redirect from `302` to `301`:

https://github.com/xwp/pwa-wp/blob/e1431eae92f75a09742c7cdd3dc438011f53fb9d/wp-includes/class-wp-https-ui.php#L358

**Comment by westonruter** [comment]
This burn-in period sounds similar to what we were thinking of for HSTS. Maybe adding HSTS could be the final step in the burn-in period, with exponential backoff of the TTL. So maybe:

* 1 week of 302 redirects, followed by 301
* then 1 week of HSTS at 60 minute TTL,
* then 1 month of HSTS at 24 hour TTL
* then permanently setting HSTS to an optimal TTL (e.g. 1 month or longer)

**Comment by kienstra** [comment]
**Redirect Code, HTTPS Notice**

Hi @westonruter and @igrigorik,
(a) Good ideas for phasing in a `301` redirect code. 


(b) Here's some possible copy for an admin notice if HTTPS is not possible, like if there's no certificate:

>HTTPS is not enabled on your site, possibly because there's no SSL certificate, or an invalid one. We strongly suggest enabling it for better security. [More details](https://make.wordpress.org/support/user-manual/web-publishing/https-for-wordpress/)

<img width="1333" alt="https-notice" src="https://user-images.githubusercontent.com/4063887/44808093-efb42100-ab90-11e8-8779-3a7f232d41fc.png">

**Comment by kienstra** [comment]
**Link For 'More details'**

Hi @igrigorik,
>For the "more details" link, are there any other pages that we could link to in the codex, that focus on the user+site owner benefits of HTTPS instead of the technical guidance? I don't think that page does a good job of motivating the claim we're proposing in the notice.

Good question. I couldn't find a page on `wordpress.org` that better describes the benefits of HTTPS.

**Comment by igrigorik** [comment]
@kienstra @westonruter could we link to the Web Fundamentals article then? Are there any best practices / requirements on links from WP dashboard?

**Comment by kienstra** [comment]
Hi @igrigorik,

Sure, I think it'd be fine to link to the [Web Fundamentals article](https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https).

>Are there any best practices / requirements on links from WP dashboard?

Good question. I couldn't find any documentation or best practices on links in the dashboard.

But it looks like all of 5 of the external links on 'Settings' pages are to the [Codex](https://codex.wordpress.org/) (in 'General Settings,' 'Writing Settings,' and 'Permalink Settings').

<img width="1167" alt="settings-pages-link-codex" src="https://user-images.githubusercontent.com/4063887/45005564-c42e9d80-afb9-11e8-954c-76ebbaa129e4.png">

**Comment by igrigorik** [comment]
I suspected as much. If there are no objections, let's go with the WF link. If there is push back down the road, we can investigate other options. I just don't feel that the current codex page on HTTPS covers the motivation sufficiently well.

**Comment by westonruter** [comment]
@igrigorik:

> Re, burn-in period: @westonruter how do you see the proposed schedule working?
> 
> * If I enable the setting, does the plugin automatically setup a 302 and later "upgrades it" to 301 without further user action?

Yes, that's right.

> * What would happen if I come in and toggle the setting on and off, would that reset the schedule?

That sounds like a good idea.

> could we link to the Web Fundamentals article then? Are there any best practices / requirements on links from WP dashboard?

For core merge proposal we would definitely need a WordPress Codex page for HTTPS. In the mean time, linking to WF is fine.

Here are all of the linked URLs that I can find in the admin: https://gist.github.com/westonruter/01d87482846aa8131afca186cad2de0f

There are only 3 exceptions to linking to WordPress.org URLs:

* http://gmpg.org/xfn/
* https://www.fsf.org/
* https://gravatar.com

**Comment by igrigorik** [comment]
>> What would happen if I come in and toggle the setting on and off, would that reset the schedule?
> That sounds like a good idea.

Hmm, there is a complication here. Once you set 301 and/or HSTS, and you uncheck the setting.. The users may still be directed to HTTPS (due to HSTS policy), and you'd need a 301 from the HTTPS back to HTTP for crawlers if you want to avoid any confusion there.

302 is safe "testing mode". Once you flip the 301 + HSTS switch though, going back is much harder. I think it's worth spending a bit more time on the UX here: how we communicate the 302 / testing, if/how the transition to 301 happens, and what happens when you try to "revert" the 301.

> For core merge proposal we would definitely need a WordPress Codex page for HTTPS. In the mean time, linking to WF is fine.

What's the process for updating codex pages? If we can update the HTTPS page to cover the why, perhaps even by linking to WF, then I'm a happy camper.

**Comment by westonruter** [comment]
> What's the process for updating codex pages? If we can update the HTTPS page to cover the why, perhaps even by linking to WF, then I'm a happy camper.

I've raised the topic in WordPress core dev chat today: https://wordpress.slack.com/archives/C02RQBWTW/p1536178915000100

I was really happy with the positive response. It was proposed that the HTTPS detection and switchover could be incorporated into a new “Site Health Check” initiative which would be merged into core, and the WordPress marketing team would include HTTPS in the materials that are presented to users to explain the importance of securing their sites.

**Comment by igrigorik** [comment]
That's awesome! What's the best way to track that discussion and is there an ETA or deadline for this?

**Comment by westonruter** [comment]
@igrigorik Probably by joining the `#core-http` Slack channel: https://wordpress.slack.com/messages/C0AHSFXSA

Also, as @schlessera [noted](https://wordpress.slack.com/archives/C02RQBWTW/p1536179214000100):

> The alert that the site is not on HTTPS could be part of the "Site Health Check" we're working on (pivot on ServeHappy).

The discussion conversation about HTTPS should probably be tracked as part of Site Health Check discussions: https://make.wordpress.org/core/?s=%22Site+Health+Check%22

This post has a roadmap: https://make.wordpress.org/core/2018/07/17/servehappy-roadmap-update-and-priorities/

> It is currently envisioned to have the first iteration ship as part of WordPress 5.0, however depending on when that version is released, this may change. It is certainly no hard deadline in that regard.

/cc @felixarntz
